import Head from 'next/head'
import styles from '@/styles/Home.module.sass'
import Sections from '@/components/sections/Sections'
import Box from '@/components/Box'
import { useEffect } from 'react'
import { gsap } from 'gsap/dist/gsap';
import { ScrollTrigger } from 'gsap/dist/ScrollTrigger';
import Image from 'next/image'
import mainImage from '../../public/img/main/main.png'

gsap.registerPlugin(ScrollTrigger);

export default function() {

  useEffect(() => {
    // const tl = gsap.timeline({
    //   scrollTrigger: {
    //     markers: true,
    //     trigger: '.box',
    //     toggleActions: 'restart pause reverse pause',
    //     scrub: 1,
    //     pin: '.box',
    //     start: "top center",
    //     end: "+=0",
    //     pinSpacing: false,
    //   }
    // });

    // tl.fromTo('.box', {
    //   duration: 1,
    //   x: 0,
    // },{
    //   duration: 1,
    //   x: 200,
    // })

    const tl = gsap.timeline();
    tl.fromTo('.main-section > img', {
      opacity: 0,
    },{
      opacity: 1,
      duration: 1,
      delay: .5
    })
    .fromTo('.main-section > div h1', {
      y: '100%',
      opacity: 0,
    },{
      y: 0,
      opacity: 1,
      duration: 1
    })
    .fromTo('.main-section > div .btn', {
      opacity: 0,
    },{
      opacity: 1,
      duration: 1,
    })
  }, [])
  

  return (
    <>
      <Head>
        <title>Mitch</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <section className={`${styles['main-section']} main-section`}>
          <Image 
            src={mainImage}
            alt='main image'
            width={320}
            height={400}
            style={{
              maxWidth: '100%',
              height: 'auto',
              borderRadius: '50%',
            }}
          />
          <div className={styles.title}>
            <h1>
              Because Art<br />
              Is Inspiration
            </h1>
            <a href='/portfolio' className='btn'>Paintings</a>
          </div>
        </section>
        

        {/* <div style={{ marginTop: '800px' }}></div>
        <Box></Box>
        <div style={{ marginTop: '800px' }}></div>
        <Sections /> */}
      </main>
    </>
  )
}
